on:
  push:
    branches:
      - master
jobs:
  pull_submodule_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Update commit author
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'          
      - name: Push to production branch
        run: |
          git checkout -b production
          git rm --cached vendor/inertia # here vendor/inertia is a submodule
          git rm .gitmodules
          rm -rf vendor/inertia/.git
          git add vendor/inertia
          git commit -m "`git log -1 --pretty=%B` + submodules"
          git push origin production -f    
